[package]
name = "nooboard-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
if-addrs.workspace = true
nooboard-config = { path = "../nooboard-config" }
nooboard-network = { path = "../nooboard-network" }
nooboard-platform = { path = "../nooboard-platform" }
nooboard-storage = { path = "../nooboard-storage" }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
nooboard-platform-macos = { path = "../nooboard-platform-macos" }

[target.'cfg(target_os = "windows")'.dependencies]
nooboard-platform-windows = { path = "../nooboard-platform-windows" }

[dev-dependencies]
tempfile.workspace = true
